version: '3.1'
services:
    api-database:
        image: mongo:latest
        container_name: "api-database"
        ports:
            - 27017:2701
    documentation-api:
        image: documentation-api
        container_name: documentation-api
        build: ./
        ports:
            - 8080:8080
        links:
            - api-database